### PR TITLE
Updated all dependencies.

### PR DESCRIPTION
**Pull request by pumken**
The following updates were made:

- Crossterm was updated from 0.15 to 0.26.1
- device_query was updated from 0.2.3 to 1.1.2
- num was updated from 0.2 to 0.4.0
- rand was updated from 0.7.2 to 0.8.5

Also removed the `package.maintenance` manifest key as it was flagged as unused by Cargo.

This commit _compiles_ but may not work as intended if APIs have changed. Probably should test the library in binaries using it.

### CODE REVIEW

**Comment by lemunozm** [comment]
Could you rebase this to get the CI works?

**Comment by pumken** [comment]
Some files in the examples folder don't compile due to API changes in the rand crate; will get this working sooner or later. (Also I used a merge instead of a rebase by accident but it might be fine idk)

**Comment by pumken** [comment]
It compiles successfully, but I've tried to run `space_invaders.rs` and `roguelike.rs` and it immediately panics due to calling `unwrap()` on the `Result` of `ct::terminal::enable_raw_mode()` with the "device not configured" and the `Result`of `ct::event::poll()` due to failure to "initialize input reader." Needs further review.

**Comment by lemunozm** [comment]
Do not worry about merging or rebasing; I'll squash the whole branch into a single commit before merging into the master.

Ok! thanks for analyzing this. Probably the `crossterm` library has changed a lot from the last version used.

**Review by lemunozm — APPROVED** [review]

**Comment by pumken** [comment]
@lemunozm This should be okay to merge; after further testing, it seems that the panicking was a result of running examples within CLion. I tested an example in the actual terminal and no panicking occurs.

**Comment by lemunozm** [comment]
Thanks @pumken !!

**Pull request merged**
